name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      app:
        description: "App folder name under apps/"
        required: true
        type: string
      context:
        description: "Build context path"
        required: false
        type: string
      dockerfile:
        description: "Path to Dockerfile"
        required: false
        type: string
      image_name:
        description: "Docker image name (e.g., username/hello-api)"
        required: true
        type: string
      push_tag:
        description: "Tag to push (e.g., latest or sha)"
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set context and Dockerfile
        if: ${{ !inputs.context || !inputs.dockerfile }}
        run: |
          # Default paths if not provided
          CONTEXT="${{ inputs.context }}"
          FILE="${{ inputs.dockerfile }}"

          if [ -z "$CONTEXT" ]; then
            CONTEXT="./apps/${{ inputs.app }}/app"
          fi
          if [ -z "$FILE" ]; then
            FILE="./apps/${{ inputs.app }}/app/Dockerfile"
          fi

          echo "CONTEXT=$CONTEXT" >> $GITHUB_ENV
          echo "DOCKERFILE=$FILE" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: |
            ${{ inputs.image_name }}:${{ inputs.push_tag }}
            ${{ inputs.image_name }}:latest
