name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      app:
        description: "App folder name under apps/"
        required: true
        type: string
      context:
        description: "Build context path"
        required: false
        default: ./apps/${{ inputs.app }}/app
        type: string
      dockerfile:
        description: "Path to Dockerfile"
        required: false
        default: ./apps/${{ inputs.app }}/app/Dockerfile
        type: string
      image_name:
        description: "Docker image name (e.g., username/hello-api)"
        required: true
        type: string
      push_tag:
        description: "Tag to push (e.g., latest or sha)"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: |
            ${{ inputs.image_name }}:${{ inputs.push_tag }}
            ${{ inputs.image_name }}:latest
